name: Deploy Site

on:
  schedule:
    - cron: '0 7 * * *' # ron on 7am every day
  # Allows manual workflow run (must in default branch to work)
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  ant-design-5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        run: |
          git clone https://github.com/ant-design/ant-design.git --depth=1

      - uses: oven-sh/setup-bun@v2
      - name: zip source
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ant-design-source.zip ./ant-design
          
      - run: cd ant-design && ls -la && bun install

      - name: add content path
        run: |
          sed -i 's/manifest: {}/runtimePublicPath: {}, manifest: {basePath: "\/mirror\/ant-design-5\/",}, base: "\/mirror\/ant-design-5\/", publicPath: "\/mirror\/ant-design-5\/"/' ./ant-design/.dumirc.ts
          sed -i 's/"devtool": false/"devtool": false,  "publicPath": "\/mirror\/ant-design-5\/"/' ./ant-design/mako.config.json
          
      - name: build site
        run: cd ant-design && bun run predeploy
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: build dist and bundle analyzer report
        run: cd ant-design && bun run dist
        env:
          ANALYZER: 1
          NODE_OPTIONS: --max_old_space_size=4096

      - name: move report.html to _site
        run: |
          if [ -f ./ant-design/report.html ]; then
            mv ./ant-design/report.html ./ant-design/_site && echo "report.html moved to _site"
          fi

      - name: replace path
        run: |
          find ./ant-design/_site -type f \( -name "*.html" -or -name "*.js" \) -exec sed -i 's/href="\//href="\/mirror\/ant-design-5\//g' {} +
          find ./ant-design/_site -type f \( -name "*.html" -or -name "*.js" \) -exec sed -i 's/src="\/umi/src="\/mirror\/ant-design-5\/umi/g' {} +
      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ant-design-5.zip ./ant-design/_site

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::ant-design-5_$(date +"%Y.%m.%d_%H_%M_%S")"
      - name: GH Release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ant-design-5.zip
            ant-design-source.zip

  pro-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        run: |
          git clone https://github.com/ant-design/pro-components.git --depth=1

      - name: zip source
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r pro-components-source.zip ./pro-components
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.1
        with:
          version: 8.12.1

      - name: add content path
        run: |
          sed -i 's/});/manifest: {basePath: "\/mirror\/pro-components\/",}, base: "\/mirror\/pro-components\/", publicPath: "\/mirror\/pro-components\/"});/' ./pro-components/.dumirc.ts
          
      - name: build site
        run: |
          cd pro-components && pnpm install && pnpm run build && pnpm run dumi
  
      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r pro-components.zip ./pro-components/dist

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::ant-design-5_$(date +"%Y.%m.%d_%H_%M_%S")"
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            pro-components.zip
            pro-components-source.zip
