name: pro-components

on:
  schedule:
    - cron: '0 7 * * *' # ron on 7am every day
  # Allows manual workflow run (must in default branch to work)
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  pro-components:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: modify commit id
        run: |
          echo "release $(date +"%Y.%m.%d_%H_%M_%S")" >> ./release.md

      - name: Merge from source branch
        id: merge
        uses: peter-evans/merge@v2
        with:
          repo: '${{ github.repository }}'
          base: main # 目标分支，默认是main，请根据需要调整
          head: main # 要合并进来的源分支，请替换为实际分支名
          method: merge
          commit-message: 'Merge branch source-branch into main' # 合并提交信息
          git-token: ${{ secrets.GITHUB_TOKEN }}

      - name: commit updated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'new release via Github Actions'
          branch: main

      - name: Checkout mirror repo
        run: |
          git clone https://github.com/ant-design/pro-components.git --depth=1

      - name: zip mirror repo source
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r pro-components-source.zip ./pro-components
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.1
        with:
          version: 8.12.1

      - name: add content path
        run: |
          sed -i 's/});/manifest: {basePath: "\/mirror\/pro-components\/",}, base: "\/mirror\/pro-components\/", publicPath: "\/mirror\/pro-components\/"});/' ./pro-components/.dumirc.ts
          
      - name: build site
        run: |
          cd pro-components && pnpm install && pnpm run build && pnpm run dumi
  
      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r pro-components.zip ./pro-components/dist

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::pro-components_$(date +"%Y.%m.%d_%H_%M_%S")"
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            pro-components.zip
            pro-components-source.zip
